name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Pac-Man
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: Shriram2617

      - name: Commit generated files
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          message: "Update Pac-Man contribution graph"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
